version: 0.2

phases:
  build:
    commands:
      - echo Started build...
      - mvn package -Dmaven.test.skip
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/shop-app.jar
  discard-paths: yes